CREATE TABLE air_quality (
    date TIMESTAMP,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    city VARCHAR(255),
    population BIGINT,
    AQI INTEGER,
    CO DOUBLE PRECISION,
    NO DOUBLE PRECISION,
    NO2 DOUBLE PRECISION,
    O3 DOUBLE PRECISION,
    SO2 DOUBLE PRECISION,
    PM2_5 DOUBLE PRECISION,
    PM10 DOUBLE PRECISION,
    NH3 DOUBLE PRECISION,
    temperature_2m DOUBLE PRECISION,
    relativehumidity_2m DOUBLE PRECISION,
    precipitation DOUBLE PRECISION,
    rain DOUBLE PRECISION,
    cloudcover DOUBLE PRECISION,
    cloudcover_low DOUBLE PRECISION,
    cloudcover_mid DOUBLE PRECISION,
    cloudcover_high DOUBLE PRECISION,
    windspeed_10m DOUBLE PRECISION,
    windspeed_100m DOUBLE PRECISION,
    winddirection_10m DOUBLE PRECISION,
    winddirection_100m DOUBLE PRECISION,
    windgusts_10m DOUBLE PRECISION,
    elevation INTEGER
);
